### ISSUE TITLE
pycollector need to be seperated from the code base

### ISSUE THREAD

**Issue by yogeshVU** [doc-vu/fecbench-server-docker#2]
It will be nice to remove the pycollector code from here. @ZhuangweiKang 
Alternate solution could be: create a dockerfile and pull the pycollector github repo into the docker container.

**Comment by ZhuangweiKang** [comment]
1. collectd subscriber has been separated from server
2. remain influxdb & amqp settings in pycollector folder, which will be copied into pycollectdsubscriber when container is creating.

**Comment by yogeshVU** [comment]
Addressed in https://github.com/doc-vu/fecbench-server-docker/commit/aef8cc7c26bfe02c82d1fd901cd421d7ee3c316c
